### PR TITLE
Missing openssl_get func

### PR DESCRIPTION
**Pull request by maghuro**

### CODE REVIEW

**Comment by maghuro** [comment]
Screenshot_20201117-072326650

**Comment by rs** [comment]
Curl is still needed later and it's too tricky to implement HTTP binary transfer with just openssl. What is your platform/distrib? Is curl not installed? Do you have wget? How did you execute the initial sh $(curl) command?

**Comment by rs** [comment]
Try again please

**Comment by maghuro** [comment]
Perfect! Thank you

**Pull request closed without merging**
